# https://taskfile.dev

version: "3"

tasks:
  lint:
    cmds:
      - pre-commit run -a

  test:
    cmds:
      - pytest

  huggingface:
    cmds:
      - python upload.py

  publish:
    cmds:
      - task: huggingface
      - pdm publish
